improved product sync
Knawat/knawat-dropshipping-magento2 pull request #78
Opened 2020-12-11 11:22 UTC by jayjittv

## :memo: Description

### :dart: Relevant issues

### :gem: Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a migration update

### :scroll: Steps to test
1. step 1
2. step 2
3. you get it...

## :vertical_traffic_light: How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2020-12-28 05:47 UTC, HazemKhaled commented
@jayjittv where we are here? if you need review please request review and update the PR description

2020-12-28 07:12 UTC, jayjittv commented
> @jayjittv where we are here? if you need review please request review and update the PR description

I have updated the description

2021-01-08 13:55 UTC, iamdharmesh requested changes

2021-01-08 13:55 UTC, iamdharmesh commented on Helper/BackgroundImport.php
> +            $lastUpdateTime = round($ts_mili);
@jayjittv Not sure if needed timezone here as date from MP always will be UTC.
Also, code can be more simple like this.
```
$datetime = new DateTime($date);
$lastUpdateTime = (int) ($datetime->getTimestamp().$datetime->format('u')/ 1000);
```

2021-01-09 04:18 UTC, jayjittv commented on Helper/BackgroundImport.php
> +            $lastUpdateTime = round($ts_mili);
I will check and verify like this

2021-01-10 10:59 UTC, HazemKhaled commented on Helper/BackgroundImport.php
>              $item['skipped']  += count($results['skipped']);
Why did we remove force_stopped?

2021-01-11 05:33 UTC, jayjittv commented on Helper/BackgroundImport.php
>              $item['skipped']  += count($results['skipped']);
@HazemKhaled 
We are still have ForceStop functionality but previously , it was adding lastImport time only in case of force stop and it was not in miliseconds , Now with improved sync I have removed forcestop condition and it will add time in case for automatic stop or force stop

2021-01-12 11:00 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Knawat/knawat-dropshipping-magento2/inspections/cc03a351-4281-49c3-9452-37334f15ab7a) was created.

2021-01-12 11:03 UTC, jayjittv commented on Helper/BackgroundImport.php
> +            $lastUpdateTime = round($ts_mili);
@HazemKhaled @iamdharmesh 
This is changed and its working without timezone now

2021-01-12 11:05 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Knawat/knawat-dropshipping-magento2/inspections/cc03a351-4281-49c3-9452-37334f15ab7a) completed: **6 new issues**

2021-02-16 13:28 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Knawat/knawat-dropshipping-magento2/inspections/788bcb3a-4e4f-4d90-b506-65b9080f00f5) was created.

2021-02-16 13:36 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Knawat/knawat-dropshipping-magento2/inspections/788bcb3a-4e4f-4d90-b506-65b9080f00f5) completed: **4 new issues**

2021-02-16 14:11 UTC, iamdharmesh commented
@jayjittv changes looks fine, but I think we need to remove pagination increase from here https://github.com/Knawat/knawat-dropshipping-magento2/blob/6ed04c213f9ebf7053bbd5f711d3d660095a5a95/Helper/BackgroundImport.php#L128 as we are saving last_update date after every batch. So, no pagination required. what do you think?

2021-02-19 10:57 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Knawat/knawat-dropshipping-magento2/inspections/1990c8c2-6ccb-4b88-9012-fe7c24705e2f) was created.

2021-02-19 11:02 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Knawat/knawat-dropshipping-magento2/inspections/1990c8c2-6ccb-4b88-9012-fe7c24705e2f) completed: **4 new issues**

2021-02-19 13:58 UTC, iamdharmesh approved these changes

2021-03-19 12:56 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Knawat/knawat-dropshipping-magento2/inspections/92939b97-56aa-4525-b2bb-624fa47d91a5) was created.

2021-03-19 13:02 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Knawat/knawat-dropshipping-magento2/inspections/92939b97-56aa-4525-b2bb-624fa47d91a5) completed: **5 new issues**

2021-03-22 09:47 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Knawat/knawat-dropshipping-magento2/inspections/e95a02a9-675b-40df-8a31-ad69b80f2e1a) was created.

2021-03-22 09:52 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Knawat/knawat-dropshipping-magento2/inspections/e95a02a9-675b-40df-8a31-ad69b80f2e1a) completed: **5 new issues**

2021-03-22 11:46 UTC, iamdharmesh approved these changes

2021-03-23 12:15 UTC, merged